### ISSUE TITLE
Factory reset and sign in triggers OTA update

### ISSUE THREAD

**Issue by parkerlreed** [npjohnson/sabrina-unlock#2]
So the factory reset is forced as part of the unlock. When you boot back up and connect to WiFi it instantly wants to download an update (even before signing in)

How are we supposed to avoid the OTA in this case?

**Comment by parkerlreed** [comment]
I see notes about removing Setup but if it can't be setup then adb can't be enabled (Unless there's a TWRP image to mess with the /system partition?)

**Comment by parkerlreed** [comment]
It's implied we have other stuff to run now besides stock... Can the Ubuntu image be flashed to this? (I never could do UBuntu as none of my USB C docks support OTG on the A ports)

Eager to mess with this, just unsure where to start.

**Comment by AfzalivE** [comment]
I haven't tried this but from the Readme:

> Yes, but you'd need to remove the SetupWraith application, or block Google's OTA servers via your router's DNS, as it will forcibly OTA you to a newer build during setup.

**Comment by parkerlreed** [comment]
Yea that's what I was pointing out. 

You can't get past setup to enable adb to them disable Setup. 

OTA blocking router level wouldn't work because 99% chance Google hardcodes 8.8.8.8 DNS on the first setup now allowing you to filter. 

Unless someone has a recovery image with adb enabled (TWRP for example) I don't see a way of doing much with this unlock. It's stuck because OTA.

**Comment by npjohnson** [comment]
I have recovery images with adb enabled and root. I'll post them this weekend.

Yeah, you'll need to flash a disabled vbmeta (which I'll also give you), and then flash/boot recovery to play with it.

From there you could select "Mount system" from "Advanced", and probably do what's needed.

If that's too complex, I can probably creat a package that has it removed... I'll look into it.

**Comment by rileyinman** [comment]
Any updates on this? I can't find the recovery or vbmeta images anywhere, and I'm not sure how to go setting up my device without being forced into an OTA.

**Comment by npjohnson** [comment]
Still working on it.

**Comment by npjohnson** [comment]
The XDA thread now has a script that allows you to bypass the first OTA in setup wizard enjoy!
