### ISSUE TITLE
[Question] Password recovery?

### ISSUE THREAD

**Issue by devenator** [npjohnson/sabrina-unlock#6]
Hi, i assume this is a stupid question, but if they enabled "the password" with an OTA-Update, would that not mean, that "the password" has to be in there somewhere? Or was this later somehow negotiated over the network (or even randomly set as Goo probably never will release it)...?

tl;dr: Is there any hope of recovering this, or should we just move on if a device is too new for unlock?

/hp

**Comment by npjohnson** [comment]
Your tldr basically nails it. If the device is too new there's not much hope.

The password is contained in the OTA yes, but it's encrypted and blown into the fuses by the TEE, which we have no insight into whatsoever. Nor will we probably it's undocumented, and intended to be the most secure facet of the device. Considering Google has extensive experience with proper tee implementations I'm really doubting we'd find anything.
