### ISSUE TITLE
Unclear on what devices are eligible

### ISSUE THREAD

**Issue by deoxal** [npjohnson/sabrina-unlock#7]
The description says there's a bootROM bug on older devices but I'm unclear if this works with the newer firmware.

A bootROM bug implies it can't be prevented totally like with the older Switches but it sounds like that's not what you're saying.

**Comment by npjohnson** [comment]
It is a bootROM bug and your understanding of the fact that can't be patched is mostly correct, the underlying vulnerability actually still exists, and you could still run this on devices distributed with modern firmware today, the dilemma is that Google decided to password protect the bootROM USB interface, which Amlogic boards allow.

It's a complex password that couldn't be brute forest in any reasonable amount of time, and Google is unwilling to distribute it.

**Comment by npjohnson** [comment]
Most older amlogic devices could use amlogic-usbdl,  unless they came with an Android 11 BSP or newer,  or  they have password mitigation enabled like sabrina.

**Comment by deoxal** [comment]
Alright thanks, I'll look for another device. Do you know of any sceeen casting software for the Raspberry Pi to mirror my 'an Android's screen.

If not, do you know what the latency for Miracast on the Dynalink or Onn box is?

**Comment by npjohnson** [comment]
Unrelated,  but I don't.

I don't use Miracast really.
