### ISSUE TITLE
how to downgrade to a unpatched stock rom

### ISSUE THREAD

**Issue by RobotsAreCrazy** [npjohnson/sabrina-unlock#9]
Hi,
about sabrina chromecast gtv

looking into this, how would i go about downgrading to a unpatched mitigation rom to unlock bootloader could i use the the 2020 rom you provided....could you possibly go over some steps for doing it please?

p.s. it is just for future info the more, the better for me and others thinking about doing it.

Thankyou

**Comment by npjohnson** [comment]
It's impossible.

Updates have a rollback counter that's hardware enforced.

Sorry, not much to be done there.

**Comment by RobotsAreCrazy** [comment]
That sucks, those early version chromecast prior to 2020 are going to become real rare if those owners aren't technically inclined as will get updated as soon as net connected is used
